version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs-frontend
    user: smartos
    restart: on-failure
    ports:
      - "5020:5000"
    volumes:
      - .:/home/smartos/app
      - ./node_modules:/home/smartos/app/node_modules
    command: /home/smartos/app/docker-entrypoint.sh
